services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=jobtrackpro
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"