apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: jobtracker-service
  labels:
    cloud.googleapis.com/location: asia-south1
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "5"
        run.googleapis.com/cpu-throttling: "true"
        run.googleapis.com/startup-cpu-boost: "true"
    spec:
      timeoutSeconds: 300
      containers:
      - image: asia-south1-docker.pkg.dev/job-tracker-pro-480917/my-repo/my-java-app:v1
        ports:
          - containerPort: 8080
        resources:
          limits:
            memory: 1Gi
            cpu: "1"
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"

        - name: JAVA_TOOL_OPTIONS
          value: "-Xms256m -Xmx512m -XX:+UseSerialGC -XX:+ExitOnOutOfMemoryError"
        
        - name: JDBC_URL
          valueFrom:
            secretKeyRef:
              name: jdbc-url
              key: latest
        - name: JDBC_USER
          valueFrom:
            secretKeyRef:
              name: jdbc-user
              key: latest
        - name: JDBC_PASS
          valueFrom:
            secretKeyRef:
              name: jdbc-pass
              key: latest

        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: gemini-api-key
              key: latest

        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: latest
        - name: JWT_REFRESH_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-refresh-secret
              key: latest
        - name: GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: google-id
              key: latest
        - name: GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: google-secret
              key: latest
        - name: GITHUB_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: github-id
              key: latest
        - name: GITHUB_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: github-secret
              key: latest
        - name: CLOUDFLARE_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: cloudflare-access-key
              key: latest
        - name: CLOUDFLARE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: cloudflare-secret-key
              key: latest
        - name: CLOUDFLARE_ENDPOINT
          value: "https://a707cb49c90aa1d9ed30f00c8559c50f.r2.cloudflarestorage.com"
        - name: CLOUDFLARE_AVATAR_BUCKET
          value: "jobtracker-avatars"
        - name: CLOUDFLARE_AVATAR_URL
          value: "https://pub-491f92cb65b94aa9a49c0a98d7d67249.r2.dev"
        - name: CLOUDFLARE_RESOURCE_BUCKET
          value: "jobtracker-resources"
        - name: CLOUDFLARE_RESOURCE_URL
          value: "https://pub-add5d47f72e7455f92e8319437d0c657.r2.dev"
        - name: EMAIL_HOST
          value: "smtp-relay.brevo.com"
        - name: EMAIL_PORT
          value: "587"
        - name: EMAIL_USER_NAME
          value: "9e4e44001@smtp-brevo.com"
        - name: EMAIL_SMTP_KEY
          valueFrom:  
            secretKeyRef:
              name: email-smtp-key
              key: latest
        - name: EMAIL_SENDER
          value: "haribabu.thatikonda3@gmail.com"
        - name: EMAIL_SENDER_NAME
          value: "Hari from JobTrackPro"
        - name: EMAIL_SENDER_ADDRESS
          value: "hyd"
        - name: GOOGLE_PUBSUB_TOPIC
          value: "projects/job-tracker-pro-480917/topics/gmail-notifications"
        - name: GOOGLE_PUBSUB_SERVICE_ACCOUNT
          value: "job-tracker-webhook-invoker@job-tracker-pro-480917.iam.gserviceaccount.com"
        - name: CRON_SECRET
          valueFrom:
            secretKeyRef:
              name: cron-secret
              key: latest