apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: jobtracker-service
  labels:
    cloud.googleapis.com/location: asia-south1
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "5"
        run.googleapis.com/cpu-throttling: "true"
        run.googleapis.com/startup-cpu-boost: "true"
    spec:
      timeoutSeconds: 300
      containers:
      - image: asia-south1-docker.pkg.dev/job-tracker-pro-480917/my-repo/my-java-app:v1
        ports:
          - containerPort: 8080
        resources:
          limits:
            memory: 1Gi
            cpu: "1"
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"

        - name: JAVA_TOOL_OPTIONS
          value: "-Xms256m -Xmx512m -XX:+UseSerialGC -XX:+ExitOnOutOfMemoryError"
        
        - name: JDBC_URL
          valueFrom:
            secretKeyRef:
              name: jdbc-url
              key: latest
        - name: JDBC_USER
          valueFrom:
            secretKeyRef:
              name: jdbc-user
              key: latest
        - name: JDBC_PASS
          valueFrom:
            secretKeyRef:
              name: jdbc-pass
              key: latest

        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: gemini-api-key
              key: latest

        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: latest
        - name: JWT_REFRESH_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-refresh-secret
              key: latest
        - name: GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: google-id
              key: latest
        - name: GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: google-secret
              key: latest
        - name: GITHUB_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: github-id
              key: latest
        - name: GITHUB_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: github-secret
              key: latest
        - name: CLOUDFLARE_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: cloudflare-access-key
              key: latest
        - name: CLOUDFLARE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: cloudflare-secret-key
              key: latest
        - name: CLOUDFLARE_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: cloudflare-endpoint
              key: latest
        - name: CLOUDFLARE_AVATAR_BUCKET
          valueFrom:
            secretKeyRef:
              name: cloudflare-avatar-bucket
              key: latest
        - name: CLOUDFLARE_AVATAR_URL
          valueFrom:
            secretKeyRef:
              name: cloudflare-avatar-url
              key: latest
        - name: CLOUDFLARE_RESOURCE_BUCKET
          valueFrom:
            secretKeyRef:
              name: cloudflare-resource-bucket
              key: latest
        - name: CLOUDFLARE_RESOURCE_URL
          valueFrom:
            secretKeyRef:
              name: cloudflare-resource-url
              key: latest
        - name: EMAIL_HOST
          valueFrom:
            secretKeyRef:
              name: email-host
              key: latest
        - name: EMAIL_PORT
          valueFrom:
            secretKeyRef:
              name: email-port
              key: latest
        - name: EMAIL_USER_NAME
          valueFrom:
            secretKeyRef:
              name: email-user-name
              key: latest
        - name: EMAIL_SMTP_KEY
          valueFrom:  
            secretKeyRef:
              name: email-smtp-key
              key: latest
        - name: EMAIL_SENDER
          valueFrom:
            secretKeyRef:
              name: email-sender
              key: latest
        - name: EMAIL_SENDER_NAME
          valueFrom:
            secretKeyRef:
              name: email-sender-name
              key: latest
        - name: EMAIL_SENDER_ADDRESS
          valueFrom:
            secretKeyRef:
              name: email-sender-address
              key: latest
        - name: GOOGLE_PUBSUB_TOPIC
          valueFrom:
            secretKeyRef:
              name: google-pubsub-topic
              key: latest
        - name: GOOGLE_PUBSUB_SERVICE_ACCOUNT
          valueFrom:
            secretKeyRef:
              name: google-pubsub-service-account
              key: latest
        - name: CRON_SECRET
          valueFrom:
            secretKeyRef:
              name: cron-secret
              key: latest