spring.application.name=JobTrackerPro
server.port=8080

# Database Connection
spring.datasource.url=${JDBC_URL}
spring.datasource.username=${JDBC_USER}
spring.datasource.password=${JDBC_PASS}
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=120000
spring.datasource.hikari.max-lifetime=300000
spring.datasource.hikari.pool-name=JobTrackerPro-HikariPool

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialec
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Gemini AI
app.gemini.enabled=true
gemini.api.key=${GEMINI_API_KEY}
gemini.api.url=https://aiplatform.googleapis.com/v1/publishers/google/models/gemini-2.5-flash-lite:generateContent


# UI url
app.ui.url=http://localhost:4200

# Base url
app.base-url=http://localhost:8080

spring.security.oauth2.client.registration.github.redirect-uri={baseUrl}/login/oauth2/code/github
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/google

# config
app.allowed.cors=http://localhost:4200
app.allowed.methods=GET,POST,PUT,DELETE,OPTIONS
app.public.endpoints=/api/auth/signup,/api/auth/login,/api/auth/refresh,/api/auth/logout,/api/auth/forgot-password,/api/auth/verify-email,/api/auth/resend-verification,/api/auth/reset-password,/oauth2/**,/api/webhooks/inbound-email,/api/webhooks/gmail/push,/api/cron/**
app.cron.secret=${CRON_SECRET:default-dev-cron-secret-123}

# JWT Secret (Must be long and secure)
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=900000
app.jwt.refresh-secret=${JWT_REFRESH_SECRET}
# 30 days
app.jwt.refresh-expiration-ms=2592000000 
app.jwt.refresh-cookie-secure=false
app.jwt.refresh-cookie-same-site=Lax

# File Upload Limits
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

spring.threads.virtual.enabled=true

# Google OAuth2
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile

app.google.pubsub-topic=${GOOGLE_PUBSUB_TOPIC}

# Webhook Security
app.security.webhook-audience=https://${NGROK_TUNNEL:localhost:8080}/api/webhooks/gmail/push
app.security.google-pubsub-service-account=${GOOGLE_PUBSUB_SERVICE_ACCOUNT}

# GITHUB OAuth2
spring.security.oauth2.client.registration.github.client-id=${GITHUB_CLIENT_ID}
spring.security.oauth2.client.registration.github.client-secret=${GITHUB_CLIENT_SECRET}
spring.security.oauth2.client.registration.github.scope=read:user,user:email

# Cloudflare R2 Config
app.storage.type=r2
cloudflare.r2.access-key=${CLOUDFLARE_ACCESS_KEY}
cloudflare.r2.secret-key=${CLOUDFLARE_SECRET_KEY}
cloudflare.r2.endpoint=${CLOUDFLARE_ENDPOINT}

# Cloudflare R2 Config - Avatars
cloudflare.r2.bucket.avatars=${CLOUDFLARE_AVATAR_BUCKET}
cloudflare.r2.public-url.avatars=${CLOUDFLARE_AVATAR_URL}

# Cloudflare R2 Config - Career Resources
cloudflare.r2.bucket.resources=${CLOUDFLARE_RESOURCE_BUCKET}
cloudflare.r2.public-url.resources=${CLOUDFLARE_RESOURCE_URL}


# Email Settings
spring.mail.host=${EMAIL_HOST}
spring.mail.port=${EMAIL_PORT}
spring.mail.username=${EMAIL_USER_NAME}
spring.mail.password=${EMAIL_SMTP_KEY}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

email.sender_email=${EMAIL_SENDER}
email.sender_name=${EMAIL_SENDER_NAME}
email.sender_address=${EMAIL_SENDER_ADDRESS}
