server.port=8080

# Postgres (local via docker)
spring.datasource.url=jdbc:postgresql://localhost:5432/jobtrackpro
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Email (MailHog for local via docker)
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false

# Default for open-source
app.gemini.enabled=false
app.storage.type=local

# JWT (Only for dev)
app.jwt.secret=9a999dhthughari45647638763748293048567832901234
app.jwt.expiration-ms=86400000

# config
app.allowed.cors=http://localhost:4200
app.allowed.methods=GET,POST,PUT,DELETE,OPTIONS
app.public.endpoints=/api/auth/signup,/api/auth/login,/api/auth/forgot-password,/api/auth/reset-password,/oauth2/**,/api/webhooks/inbound-email,/api/storage/files/**

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# UI url
app.ui.url=http://localhost:4200

# Base url
app.base-url=http://localhost:8080

spring.security.oauth2.client.registration.github.redirect-uri={baseUrl}/login/oauth2/code/github
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/google


# File Upload Limits
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# Google OAuth2
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile

# GITHUB OAuth2
spring.security.oauth2.client.registration.github.client-id=${GITHUB_CLIENT_ID}
spring.security.oauth2.client.registration.github.client-secret=${GITHUB_CLIENT_SECRET}
spring.security.oauth2.client.registration.github.scope=read:user,user:email

email.sender_email=haribabu.thatikonda3@gmail.com
email.sender_name=Hari from JobTrackPro
email.sender_address=JobTrackPro <haribabu.thatikonda3@gmail.com>
