name: Deploy to Cloud Run
run-name: "Deploy #${{ github.run_number }}: ${{ github.event.head_commit.message || github.sha }} by @${{ github.actor }}"


on:
  workflow_dispatch:

env:
  PROJECT_ID: job-tracker-pro-480917
  REGION: asia-south1
  REPO_NAME: my-repo 
  SERVICE_NAME: jobtracker-service
  IMAGE_NAME: my-java-app

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deployment Summary
      run: |
        FULL_MSG=$(git log -1 --pretty=%B)
        SUBJECT=$(git log -1 --pretty=%s)
        AUTHOR=$(git log -1 --pretty=%an)
        
        echo "::notice title= DEPLOYING COMMIT::$SUBJECT"

        echo "# Deployment details" >> $GITHUB_STEP_SUMMARY
        echo "## Commit Message" >> $GITHUB_STEP_SUMMARY
        echo "> ### $SUBJECT" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "---" >> $GITHUB_STEP_SUMMARY
        echo "### Metadata" >> $GITHUB_STEP_SUMMARY
        echo "- **Author:** $AUTHOR" >> $GITHUB_STEP_SUMMARY
        echo "- **Status:** Processing..." >> $GITHUB_STEP_SUMMARY
        
        # Save to environment
        echo "COMMIT_MESSAGE=$SUBJECT" >> $GITHUB_ENV

    - name: Google Auth
      id: auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: Docker Auth
      run: |
        gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

    - name: Build and Push Container
      run: |
        TAG="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"
        docker build -t $TAG ./backend
        docker push $TAG
        echo "IMAGE_TAG=$TAG" >> $GITHUB_ENV

    - name: Update Service YAML
      run: |
        sed -i "s|image: .*|image: ${{ env.IMAGE_TAG }}|g" backend/service.yaml
        sed -i "/template:/a \    metadata:\n      annotations:\n        run.googleapis.com/description: \"${{ env.COMMIT_MESSAGE }}\"" backend/service.yaml
        cat backend/service.yaml # verify content in logs

    - name: Deploy to Cloud Run
      uses: google-github-actions/deploy-cloudrun@v2
      with:
        metadata: backend/service.yaml
        region: ${{ env.REGION }}
